### ISSUE TITLE
FetchError: request to https://raw.githubusercontent.com/vercel/next.js/v9.4.5-canary.6/docs/manifest.json failed, reason: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by tarvos21** [vercel/next-site#746]
I got an error when trying to 'yarn dev' or 'yarn build'.

Error in the terminal:

```
FetchError: request to https://raw.githubusercontent.com/vercel/next.js/v9.4.5-canary.6/docs/manifest.json failed, reason: connect ECONNREFUSED 0.0.0.0:443
    at ClientRequest.<anonymous> (/Users/bing/develop/next-site/node_modules/next/dist/compiled/node-fetch/index.js:1:147710)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

Error in the browser:

```
Server Error
Error: request to https://raw.githubusercontent.com/vercel/next.js/v9.4.5-canary.6/docs/manifest.json failed, reason: connect ECONNREFUSED 0.0.0.0:443
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown> (FetchError: request to

https://raw.githubusercontent.com/vercel/next.js/v9.4.5-canary.6/docs/manifest.json%20failed,%20reason:%20connect%20ECONNREFUSED%200.0.0.0 (443)
ClientRequest.<anonymous>

file:///Users/bing/develop/next-site/node_modules/next/dist/compiled/node-fetch/index.js (1:147710)
ClientRequest.emit

events.js (315:20)
TLSSocket.socketErrorListener

_http_client.js (432:9)
TLSSocket.emit

events.js (315:20)
emitErrorNT

internal/streams/destroy.js (84:8)
processTicksAndRejections

internal/process/task_queues.js (84:21)
```

Anyone has a clue about the error?

**Comment by darthvader2** [comment]
kill  your ports and try running it again, this should work 

it worked for me.

**Comment by tarvos21** [comment]
> kill your ports and try running it again, this should work
> 
> it worked for me.

Thanks, I tried to kill 443 and 3000, nothing changed. 

I only get the error when go to '/docs' route, any idea about the problem?
